### PR TITLE
resin/__init__: remove unused import

### PR DESCRIPTION
**Pull request by chibby0ne**
Change-type: patch
Signed-off-by: Antonio Gutierrez <chibby0ne@gmail.com>

### CODE REVIEW

**Comment by nghiant2710** [comment]
@chibby0ne, thank you for the PR, since our CI won't work with external branch so can you change your PR to this branch https://github.com/resin-io/resin-sdk-python/tree/remove-unused-import. 

Also please change the message from `resin/__init__: remove unused import` to `resin/__init__: Remove unused import` so our CI won't complain about it.

**Comment by chibby0ne** [comment]
Hi @nghiant2710 thanks for the reply. In the future I may want to contribute to resin's repos, what would be the best approach to follow to avoid these kinds of issues?

**Comment by chibby0ne** [comment]
@nghiant2710  BTW forgot to mention, I changed the base of the PR as you asked, and also the commit message as required: https://github.com/resin-io/resin-sdk-python/pull/104

**Comment by chibby0ne** [comment]
Already merged in #104

**Pull request closed without merging**
