### PR TITLE
Remove __future__ imports

### PR DESCRIPTION
**Pull request by Siecje**
These imports were for supporting Python2

### CODE REVIEW

**Comment by nghiant2710** [comment]
Hey @Siecje, thank you for the PR, LGTM 👍 but can you please add the `change-type` and `sign-off` to your commit message (like the example below) to make our CI happy?

```
Change-type: patch
Signed-off-by: Trong Nghia Nguyen [nghiant2710@gmail.com](mailto:nghiant2710@gmail.com)
```

Then I would be happy to merge this.

**Comment by Siecje** [comment]
@nghiant2710 Done.

**Comment by nghiant2710** [comment]
@Siecje, so sorry for not making this clear to you, since you are the author of the PR so please put your information in the `sign-off`. Mine was just an example :)

**Comment by nghiant2710** [comment]
Or if you don't want to add your information then just `Change-type` is enough.

**Review by nghiant2710 — APPROVED** [review]

**Pull request merged**
